sonar.projectKey=aphichat1835-coder_Discord-Bot
sonar.organization=aphichat1835-coder
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=discord,scripts
sonar.tests=discord/tests,verification-tests
sonar.exclusions=discord/tests/**,discord/public/**,discord/views/**
sonar.test.inclusions=discord/tests/**/*.test.js,verification-tests/**/*.test.js
sonar.coverage.exclusions=discord/tests/**,verification-tests/**,discord/public/**,discord/views/**
sonar.javascript.lcov.reportPaths=coverage/discord.lcov,coverage/voice.lcov,coverage/verification.lcov
sonar.qualitygate.wait=true
